version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopass
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: todo-flask
    depends_on:
      - db
    ports:
      - "5000:5000"
